name: Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - run: |
          touch .env.production
          echo REACT_APP_API_URL=${{ secrets.API_URL }} >> .env.production
      - name: Build
        run: |
          yarn install
          yarn build
      - name: Clean
        uses: appleboy/ssh-action@master
        with:
          host: "${{ secrets.HOST }}"
          username: "${{ secrets.USER }}"
          key: "${{ secrets.PRIVATE_KEY }}"
          script: |
            cd /var/www/html
            rm -rf teacup/
      - name: Deploy
        uses: horochx/deploy-via-scp@1.1.0
        with:
          local: build/*
          remote: /var/www/html/teacup
          host: "${{ secrets.HOST }}"
          user: "${{ secrets.USER }}"
          key: "${{ secrets.PRIVATE_KEY }}"
