name: Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "15.x"
      - name: Build
        run: |
          yarn install
          yarn build
      - name: Deploy
        uses: horochx/deploy-via-scp@1.1.0
        with:
          local: build/*
          remote: /var/www/html
          host: "${{ secrets.HOST }}"
          user: "${{ secrets.USER }}"
          key: "${{ secrets.PRIVATE_KEY }}"
